package com.ecommerce.ecommerce.status;

public enum Status {
    SUCCESS,
    USER_ALREADY_EXISTS,
    FAILURE,
    EMAIL_ALREADY_EXISTS,
    PRODUCT_ALREADY_EXISTS,
    PRODUCT_NOT_FOUND,
    CART_ITEM_NOT_FOUND,
    USER_ID_NOT_EXISTS,
    UPC_NOT_EXISTS,

    ADDRESS_NOT_FOUND
}
